# Generated by Django 4.2.3 on 2023-11-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attachment1_ulica'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment1',
            name='zaklad_pracy',
            field=models.CharField(default='zaklad', max_length=150),
        ),
    ]
