# Generated by Django 4.2.3 on 2023-11-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attachment1_zaklad_pracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment1',
            name='zaklad_pracy',
            field=models.CharField(max_length=150),
        ),
    ]
