# Generated by Django 4.2.3 on 2023-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_attachment1_zaklad_pracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dziekan_wydzialu', models.CharField(max_length=255)),
                ('start_praktyk', models.DateField()),
                ('koniec_praktyk', models.DateField()),
            ],
        ),
    ]
