# Generated by Django 4.2.3 on 2023-11-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment1',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
