# Generated by Django 4.2.7 on 2023-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_attachment1_koniec_praktyk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment1',
            name='kontakt1_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='kontakt1_imie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='kontakt1_tel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='kontakt2_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='kontakt2_imie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='kontakt2_tel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='krs',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='nip',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='attachment1',
            name='regon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
